### ISSUE TITLE
Occasional exception in JavacFileManager when scanning the platform classpath

### ISSUE THREAD

**Issue by Sipkab** [sakerbuild/saker.java.compiler#16]
Some exceptions happened on CI when testing on JDK 10, in which various runtime exceptions were thrown in JavacFileManager.

Attached logs from Azure Pipelines. The bug was first encountered at commit e7b6ae49baaa8df3a645c8441ebb738c337a43e7, but likely not related to that.

[exc1.log](https://github.com/sakerbuild/saker.java.compiler/files/10290015/exc1.log)
[exc2.log](https://github.com/sakerbuild/saker.java.compiler/files/10290016/exc2.log)
[exc3.log](https://github.com/sakerbuild/saker.java.compiler/files/10290019/exc3.log)

**Comment by Sipkab** [comment]
[exc4.log](https://github.com/sakerbuild/saker.java.compiler/files/10293945/exc4.log)

**Comment by Sipkab** [comment]
JVM logs (using `-Xlog`) during testing shows the following trace for the `NullPointerException`:

```
[85.437s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f004235ca70} 'visitPackageLocation' '(Ljdk/internal/jimage/ImageLocation;)V' in 'jdk/internal/jimage/ImageReader$SharedImageReader'>
 at bci 163 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f004235ccc0} 'handlePackages' '(Ljava/lang/String;Ljdk/internal/jimage/ImageLocation;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jimage/ImageReader$SharedImageReader'>
 at bci 100 for thread 0x00007f006005d000
[85.438s][info][exceptions] 69401 [Exception (): a 'java/lang/NullPointerException'{0x0000000098e3d740} in {method} {0x00007f004235d2a0} 'findNode' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jimage/ImageReader$SharedImageReader' at 0x00007f006e8556e4]
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f004235dbc0} 'lambda$handlePackages$0' '(Ljdk/internal/jimage/ImageLocation;)V' in 'jdk/internal/jimage/ImageReader$SharedImageReader'>
 at bci 5 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f0020e6ab90} 'visit' '(Ljdk/internal/jimage/ImageLocation;)V' in 'jdk/internal/jimage/ImageReader$SharedImageReader$$Lambda$1581'>
 at bci 5 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f004235c870} 'visitLocation' '(Ljdk/internal/jimage/ImageLocation;Ljdk/internal/jimage/ImageReader$SharedImageReader$LocationVisitor;)V' in 'jdk/internal/jimage/ImageReader$SharedImageReader'>
 at bci 61 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f004235ccc0} 'handlePackages' '(Ljava/lang/String;Ljdk/internal/jimage/ImageLocation;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jimage/ImageReader$SharedImageReader'>
 at bci 25 for thread 0x00007f006005d000
[85.438s][info][exceptions] 69402 [Exception (): a 'java/lang/NullPointerException'{0x0000000098e3d740} in {method} {0x00007f004235d2a0} 'findNode' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jimage/ImageReader$SharedImageReader' at 0x00007f006e8556e4]
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f0042358f28} 'findNode' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jimage/ImageReader'>
 at bci 9 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f0043a0c978} 'findNode' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jrtfs/SystemImage$1'>
 at bci 5 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/lang/NullPointerException'{0x0000000098e3d740}>
 thrown in interpreter method <{method} {0x00007f00439e6eb0} 'lookup' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jrtfs/JrtFileSystem'>
 at bci 5 for thread 0x00007f006005d000
[85.438s][info][exceptions] Exception <a 'java/nio/file/InvalidPathException'{0x0000000098e3dcd0}: java.lang.NullPointerException>
 thrown in interpreter method <{method} {0x00007f00439e6eb0} 'lookup' '(Ljava/lang/String;)Ljdk/internal/jimage/ImageReader$Node;' in 'jdk/internal/jrtfs/JrtFileSystem'>
 at bci 22 for thread 0x00007f006005d000
```

**Comment by Sipkab** [comment]
Two strange things are:
1. These errors have only been experienced when running the tests on JDK 10.
2. Based on the code of `SharedImageReader`, the `nodes` Map should contain the `Directory` that is being retrieved. This is because `visitPackageLocation` is being called from `handlePackages` just right after the new directory with that name is being created.

No 2. makes this seem like the `SharedImageReader` is being closed concurrently by someone other, as the `nodes` Map only gets cleared in the `jdk.internal.jimage.ImageReader.SharedImageReader.close(ImageReader)` function.

Might be because of some GC finalization, or because the deffered close functionality of `JavacFileManager`?

**Comment by Sipkab** [comment]
Also the testing seems to get stuck (or in an infinite loop) sometimes at `DirectoryModulePathTaskTest`.

**Comment by Sipkab** [comment]
Something feels broken in the JDK 10 release. Recently received an exception from ProxyGenerator:
```
2022-12-26T15:39:19.5824533Z [saker.java.test]	Caused by: java.lang.InternalError: late constant pool addition: ()Lsaker/java/compiler/main/compile/option/SourceVersionTaskOption;
2022-12-26T15:39:19.5825138Z [saker.java.test]		at java.base/java.lang.reflect.ProxyGenerator$ConstantPool.getValue(ProxyGenerator.java:1884)
2022-12-26T15:39:19.5825723Z [saker.java.test]		at java.base/java.lang.reflect.ProxyGenerator$ConstantPool.getUtf8(ProxyGenerator.java:1739)
2022-12-26T15:39:19.5826299Z [saker.java.test]		at java.base/java.lang.reflect.ProxyGenerator$MethodInfo.write(ProxyGenerator.java:818)
2022-12-26T15:39:19.5826854Z [saker.java.test]		at java.base/java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:560)
```
[exc_logs_ProxyGenerator.log](https://github.com/sakerbuild/saker.java.compiler/files/10304061/exc_logs_ProxyGenerator.log)

This really should not happen, and only happened once, on JDK 10. Can't reliably reproduce.
As JDK 10 is an older version, and no longer actively supported, I'll remove the testing for JDK 10 on CI, to avoid dealing with these errors. Will look into it if the errors surface on other JDK releases, but until then, I consider this to be a JDK 10 specific bug with unknown cause.
